print("Hello There let's learn Python Operator")
("")
Bilangan_a=input("Masukkan Bilangan Pertama: ")
Bilangan_b=input("Masukkan Bilangan Kedua: ")
print("Bilangan yang anda masukkan adalah: ", Bilangan_a,"&", Bilangan_b)
Summary=int(Bilangan_a) + int(Bilangan_b)
Kurang=int(Bilangan_a) - int(Bilangan_b)
Kali=int(Bilangan_a) * int(Bilangan_b)
Bagi=int(Bilangan_a) / int(Bilangan_b)
Pangkat=int(Bilangan_a) ** int(Bilangan_b)
Modulus=int(Bilangan_a) % int(Bilangan_b)
print("Hasil Penjumlahan Bilangan Pertama dan Bilangan Kedua adalah: ", Summary)
print("Hasil Pengurangan Bilangan Pertama dan Bilangan Kedua adalah: ", Kurang)
print("Hasil Perkalian Bilangan Pertama dan Bilangan Kedua adalah: ", Kali)
print("Hasil Pembagian Bilangan Pertama dan Bilangan Kedua adalah: ", Bagi)
print("Hasil Sisa Pembagian Bilangan Pertama dan Bilangan Kedua adalah: ", Modulus)
print("Hasil Operasi Pangkat Bilangan Pertama dan Bilangan Kedua adalah: ", Pangkat)
if int(Summary)%2==0:
    print ("Hasil Sisa Penjumlahan Bilangan Pertama & Kedua adalah Bilangan Genap")
else:
    print ("Hasil Sisa Penjumlahan Bilangan Pertama & Kedua adalah Bilangan Ganjil")